name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I searched existing issues
          required: true
        - label: I'm using the latest version
          required: true

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import the library with '...'
        2. Call function with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: 💻 Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { createAsyncStorage } from '@stork-tools/zod-async-storage';
        
        // Your code here that reproduces the issue
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      value: |
        - Package version: 
        - React Native version: 
        - Platform: (iOS/Android/Both)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      placeholder: Screenshots, logs, or other relevant information...
    validations:
      required: false
