name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I searched existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: 🔧 API Design (if applicable)
      description: How would you like this feature to work? Provide example code or API design
      render: typescript
      placeholder: |
        // Example of how the feature might work
        import { createAsyncStorage } from '@stork-tools/zod-async-storage';
        
        const storage = createAsyncStorage({
          // Your proposed API here
        });
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: I also considered... / Another approach could be...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: 📋 Use Cases
      placeholder: When would this be useful?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      placeholder: Any other context, examples, or ideas...
    validations:
      required: false
